version: '3'

services:

  mysql-development:
    image: mysql:8.0.27
    environment:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: authcrudlatest
  MYSQL_USER: root
  ports:
    - "3306:3306"
  extra_hosts:
    - "host.docker.internal:host-gateway"